<a href="https://colab.research.google.com/github/zeynepdnnz/cs445-semeval-task5/blob/main/CS445_STS_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Setup and Imports**

In [1]:
!pip install -q "transformers>=4.40,<4.45"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 128.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 46.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 63.1 MB/s eta 0:00:00

In [ ]:
from google.colab import drive
drive.mount('/')

In [3]:
import pandas
from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    TrainingArguments, Trainer, BatchEncoding,
    DataCollatorWithPadding, EvalPrediction,
    EarlyStoppingCallback
    )
from datasets import Dataset, DatasetDict, load_dataset, Value
import numpy as np
from scipy.stats import spearmanr

In [4]:
model_id = "MoritzLaurer/deberta-v3-large-zeroshot-v2.0"
tokenizer = AutoTokenizer.from_pretrained(model_id)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

In [5]:
def input_format(sample: pandas.Series) -> tuple[str, str]:
  story_part = [sample['precontext'], sample['sentence'], sample['ending'] or '']
  story_part = " ".join(story_part)
  meaning_part = (f"{sample['homonym']}: {sample['judged_meaning']} "
                   f"(e.g., \"{sample['example_sentence']}\")")

  return story_part, meaning_part


def tokenize_ambistory(batch: dict) -> BatchEncoding:
    story_parts = []
    meaning_parts = []
    for i in range(len(batch["precontext"])):
        ending = batch["ending"][i] or ''
        story = f"{batch['precontext'][i]} {batch['sentence'][i]} {ending}"
        meaning = (
            f"{batch['homonym'][i]}: {batch['judged_meaning'][i]} "
            f'(e.g., "{batch["example_sentence"][i]}")'
        )
        story_parts.append(story)
        meaning_parts.append(meaning)

    return tokenizer(
        story_parts,
        meaning_parts,
        truncation="only_first",
        max_length=256,
        padding=False,
    )

def tokenize_stsb(batch: dict) -> BatchEncoding:
    return tokenizer(
        batch["sentence1"],
        batch["sentence2"],
        truncation="only_first",
        max_length=256,
        padding=False
    )


def metric_computation(eval_pred: EvalPrediction) -> dict[str, float]:
  predictions, labels = eval_pred
  predictions = predictions.squeeze()

  spearman_score, _ = spearmanr(predictions, labels)

  mean_absolute_error = np.mean(np.abs(predictions-labels))
  root_mean_squared_error = np.sqrt(np.mean((predictions-labels)**2))

  return {
      "spearman": spearman_score,
      "mae": mean_absolute_error,
      "rmse": root_mean_squared_error
  }

# **Datasets**

In [6]:
ambistory_train_df = pandas.read_json("/content/train.json").T
ambistory_validation_df = pandas.read_json("/content/dev.json").T
ambistory_test_df = pandas.read_json("/content/test.json").T

In [7]:
raw_datasets = DatasetDict({
    "ambistory_train_set": Dataset.from_pandas(ambistory_train_df),
    "ambistory_validation_set": Dataset.from_pandas(ambistory_validation_df),
    "ambistory_test_set": Dataset.from_pandas(ambistory_test_df)
})

for split_name in raw_datasets:
    raw_datasets[split_name] = raw_datasets[split_name].rename_column("average", "labels")

for split_name in raw_datasets:
    raw_datasets[split_name] = raw_datasets[split_name].cast_column("labels", Value("float32"))

print(raw_datasets["ambistory_train_set"].column_names)

cols_to_remove = [c for c in raw_datasets["ambistory_train_set"].column_names if c != "labels"]

tokenized_datasets = raw_datasets.map(
    tokenize_ambistory,
    batched=True,
    remove_columns=cols_to_remove,
)

Casting the dataset:   0%|          | 0/2280 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/588 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/930 [00:00<?, ? examples/s]

['homonym', 'judged_meaning', 'precontext', 'sentence', 'ending', 'choices', 'labels', 'stdev', 'nonsensical', 'sample_id', 'example_sentence', '__index_level_0__']

Map:   0%|          | 0/2280 [00:00<?, ? examples/s]

Map:   0%|          | 0/588 [00:00<?, ? examples/s]

Map:   0%|          | 0/930 [00:00<?, ? examples/s]

In [8]:
stsb = load_dataset("glue", "stsb")

stsb = stsb.rename_column("label", "labels")
stsb = stsb.map(lambda x: {"labels": float(x["labels"])})
stsb_tokenized = stsb.map(
    tokenize_stsb,
    batched=True,
    remove_columns=[c for c in stsb["train"].column_names if c != "labels"],
)

README.md: 0.00B [00:00, ?B/s]

stsb/train-00000-of-00001.parquet:   0%|          | 0.00/502k [00:00<?, ?B/s]

stsb/validation-00000-of-00001.parquet:   0%|          | 0.00/151k [00:00<?, ?B/s]

stsb/test-00000-of-00001.parquet:   0%|          | 0.00/114k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/5749 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1500 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1379 [00:00<?, ? examples/s]

Map:   0%|          | 0/5749 [00:00<?, ? examples/s]

Map:   0%|          | 0/1500 [00:00<?, ? examples/s]

Map:   0%|          | 0/1379 [00:00<?, ? examples/s]

Map:   0%|          | 0/5749 [00:00<?, ? examples/s]

Map:   0%|          | 0/1500 [00:00<?, ? examples/s]

Map:   0%|          | 0/1379 [00:00<?, ? examples/s]

# **STS-B Pretraining**

In [10]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_id,
    num_labels=1,
    problem_type="regression",
    ignore_mismatched_sizes=True,
)

stsb_args = TrainingArguments(
    output_dir="./curriculum_stsb",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    num_train_epochs=4,
    weight_decay=0.01,
    warmup_ratio=0.1,
    bf16=True,
    load_best_model_at_end=True,
    metric_for_best_model="spearman",
    greater_is_better=True,
    save_total_limit=2,
    logging_steps=100,
    report_to="none",
    seed=42,
)

stsb_trainer = Trainer(
    model=model,
    args=stsb_args,
    data_collator=data_collator,
    train_dataset=stsb_tokenized["train"],
    eval_dataset=stsb_tokenized["validation"],
    tokenizer=tokenizer,
    compute_metrics=metric_computation,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

stsb_trainer.train()

stsb_trainer.save_model("./curriculum_stsb/final")

# ---- STAGE 2: AmbiStory fine-tuning on top of STS-B ----

model = AutoModelForSequenceClassification.from_pretrained(
    "./curriculum_stsb/final",
    num_labels=1,
    problem_type="regression",
)

ambistory_args = TrainingArguments(
    output_dir="./curriculum_stsb_ambistory",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-6,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=64,
    num_train_epochs=5,
    weight_decay=0.01,
    warmup_ratio=0.06,
    bf16=True,
    load_best_model_at_end=True,
    metric_for_best_model="spearman",
    greater_is_better=True,
    save_total_limit=2,
    logging_steps=50,
    report_to="none",
    seed=1337,
)

ambistory_trainer = Trainer(
    model=model,
    args=ambistory_args,
    data_collator=data_collator,
    train_dataset=tokenized_datasets["ambistory_train_set"],
    eval_dataset=tokenized_datasets["ambistory_validation_set"],
    tokenizer=tokenizer,
    compute_metrics=metric_computation,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
)

ambistory_trainer.train()

test_metrics = ambistory_trainer.evaluate(tokenized_datasets["ambistory_test_set"])

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at MoritzLaurer/deberta-v3-large-zeroshot-v2.0 and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([2]) in the checkpoint and torch.Size([1]) in the model instantiated
- classifier.weight: found shape torch.Size([2, 1024]) in the checkpoint and torch.Size([1, 1024]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [11]:
print(test_metrics)

{'eval_loss': 0.9686604738235474, 'eval_spearman': 0.64513699281547, 'eval_mae': 0.7680975794792175, 'eval_rmse': 0.9842054843902588, 'eval_runtime': 1.548, 'eval_samples_per_second': 600.775, 'eval_steps_per_second': 9.69, 'epoch': 5.0}

# **STS-B Contribution Check Across Different Seeds**

In [12]:
import json
import gc
import torch
import numpy as np
from pathlib import Path

# ---------- locked curriculum config ----------

STSB_CONFIG = {
    "lr": 2e-5,
    "bs": 16,
    "epochs": 4,
    "warmup": 0.1,
}

AMBISTORY_CONFIG = {
    "lr": 5e-6,
    "bs": 8,
    "epochs": 5,
    "warmup": 0.06,
}

SEEDS = [42, 1337, 2024]


def run_curriculum(seed):
    """Run STS-B → AmbiStory pipeline with given seed. Returns dev + test metrics."""

    # === STAGE 1: STS-B ===

    model = AutoModelForSequenceClassification.from_pretrained(
        model_id,
        num_labels=1,
        problem_type="regression",
        ignore_mismatched_sizes=True,
    )

    stsb_args = TrainingArguments(
        output_dir=f"./curriculum_runs/stsb_seed{seed}",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=STSB_CONFIG["lr"],
        per_device_train_batch_size=STSB_CONFIG["bs"],
        per_device_eval_batch_size=64,
        num_train_epochs=STSB_CONFIG["epochs"],
        weight_decay=0.01,
        warmup_ratio=STSB_CONFIG["warmup"],
        bf16=True,
        load_best_model_at_end=True,
        metric_for_best_model="spearman",
        greater_is_better=True,
        save_total_limit=1,
        logging_steps=200,
        report_to="none",
        seed=seed,
        disable_tqdm=True,
    )

    stsb_trainer = Trainer(
        model=model,
        args=stsb_args,
        data_collator=data_collator,
        train_dataset=stsb_tokenized["train"],
        eval_dataset=stsb_tokenized["validation"],
        tokenizer=tokenizer,
        compute_metrics=metric_computation,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )

    stsb_trainer.train()

    stsb_dev_spearman = stsb_trainer.state.best_metric
    print(f"  Stage 1 (STS-B): dev Spearman = {stsb_dev_spearman:.4f}")

    stage1_ckpt = f"./curriculum_runs/stsb_seed{seed}/final"
    stsb_trainer.save_model(stage1_ckpt)

    del model, stsb_trainer
    gc.collect()
    torch.cuda.empty_cache()

    # === STAGE 2: AmbiStory ===

    model = AutoModelForSequenceClassification.from_pretrained(stage1_ckpt)

    ambi_args = TrainingArguments(
        output_dir=f"./curriculum_runs/ambistory_seed{seed}",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=AMBISTORY_CONFIG["lr"],
        per_device_train_batch_size=AMBISTORY_CONFIG["bs"],
        per_device_eval_batch_size=64,
        num_train_epochs=AMBISTORY_CONFIG["epochs"],
        weight_decay=0.01,
        warmup_ratio=AMBISTORY_CONFIG["warmup"],
        bf16=True,
        load_best_model_at_end=True,
        metric_for_best_model="spearman",
        greater_is_better=True,
        save_total_limit=1,
        logging_steps=100,
        report_to="none",
        seed=seed,
        disable_tqdm=True,
    )

    ambi_trainer = Trainer(
        model=model,
        args=ambi_args,
        data_collator=data_collator,
        train_dataset=tokenized_datasets["ambistory_train_set"],
        eval_dataset=tokenized_datasets["ambistory_validation_set"],
        tokenizer=tokenizer,
        compute_metrics=metric_computation,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
    )

    ambi_trainer.train()

    ambi_dev_spearman = ambi_trainer.state.best_metric

    eval_logs = [
        log for log in ambi_trainer.state.log_history
        if "eval_spearman" in log and not np.isnan(log["eval_spearman"])
    ]
    best_log = max(eval_logs, key=lambda x: x["eval_spearman"])
    best_epoch = best_log["epoch"]

    test_metrics = ambi_trainer.evaluate(tokenized_datasets["ambistory_test_set"])

    test_preds = ambi_trainer.predict(tokenized_datasets["ambistory_test_set"]).predictions.squeeze()
    test_labels = ambistory_test_df["average"].to_numpy()
    test_stdev = ambistory_test_df["stdev"].to_numpy()
    threshold = np.maximum(test_stdev, 1.0)
    acc_within_sd = float(np.mean(np.abs(test_preds - test_labels) <= threshold))

    del model, ambi_trainer
    gc.collect()
    torch.cuda.empty_cache()

    return {
        "stsb_dev_spearman": float(stsb_dev_spearman),
        "ambi_dev_spearman": float(ambi_dev_spearman),
        "ambi_best_epoch": float(best_epoch),
        "test_spearman": float(test_metrics["eval_spearman"]),
        "test_mae": float(test_metrics["eval_mae"]),
        "test_rmse": float(test_metrics["eval_rmse"]),
        "test_acc_within_sd": acc_within_sd,
        "dev_test_gap": float(ambi_dev_spearman - test_metrics["eval_spearman"]),
    }


Path("./curriculum_runs").mkdir(exist_ok=True)
results = {}

for seed in SEEDS:
    print(f"\n{'='*60}")
    print(f"Seed {seed}")
    print('='*60)

    metrics = run_curriculum(seed)
    results[seed] = metrics

    print(f"  → STS-B dev:    {metrics['stsb_dev_spearman']:.4f}")
    print(f"  → Ambi dev:     {metrics['ambi_dev_spearman']:.4f} (best epoch {metrics['ambi_best_epoch']:.0f})")
    print(f"  → Test ρ:       {metrics['test_spearman']:.4f}")
    print(f"  → Test acc-SD:  {metrics['test_acc_within_sd']:.4f}")
    print(f"  → Dev-test gap: {metrics['dev_test_gap']:.4f}")

    with open("./curriculum_runs/multiseed_results.json", "w") as f:
        json.dump(results, f, indent=2)


print("\n\n" + "="*60)
print("MULTI-SEED CURRICULUM RESULTS (STS-B -> AmbiStory)")
print("="*60)

test_spearmans = [r["test_spearman"] for r in results.values()]
test_acc_sds = [r["test_acc_within_sd"] for r in results.values()]
dev_spearmans = [r["ambi_dev_spearman"] for r in results.values()]
gaps = [r["dev_test_gap"] for r in results.values()]
best_epochs = [r["ambi_best_epoch"] for r in results.values()]

print(f"\nTest Spearman:        {np.mean(test_spearmans):.4f} ± {np.std(test_spearmans):.4f}")
print(f"Test Acc-within-SD:   {np.mean(test_acc_sds):.4f} ± {np.std(test_acc_sds):.4f}")
print(f"AmbiStory dev ρ:      {np.mean(dev_spearmans):.4f} ± {np.std(dev_spearmans):.4f}")
print(f"Dev -> test gap:       {np.mean(gaps):.4f} ± {np.std(gaps):.4f}")
print(f"Best epoch (Stage 2): {np.mean(best_epochs):.1f} (range: {min(best_epochs):.0f}–{max(best_epochs):.0f})")

print(f"\nPer seed:")
for seed, r in results.items():
    print(f"  seed={seed}: test ρ={r['test_spearman']:.4f}, gap={r['dev_test_gap']:.4f}, best_epoch={r['ambi_best_epoch']:.0f}")

BASELINE_TEST_SPEARMAN = 0.6336
BASELINE_TEST_ACC_SD = 0.7742
BASELINE_DEV_TEST_GAP = 0.681 - 0.6336

print(f"\nVs baseline (single seed):")
print(f"  Δ Test Spearman:    {np.mean(test_spearmans) - BASELINE_TEST_SPEARMAN:+.4f}")
print(f"  Δ Test Acc-SD:      {np.mean(test_acc_sds) - BASELINE_TEST_ACC_SD:+.4f}")
print(f"  Δ Dev-test gap:     {np.mean(gaps) - BASELINE_DEV_TEST_GAP:+.4f}")

============================================================
Seed 42
============================================================

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at MoritzLaurer/deberta-v3-large-zeroshot-v2.0 and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([2]) in the checkpoint and torch.Size([1]) in the model instantiated
- classifier.weight: found shape torch.Size([2, 1024]) in the checkpoint and torch.Size([1, 1024]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'loss': 2.2625, 'grad_norm': 10.288454055786133, 'learning_rate': 1.9135802469135804e-05, 'epoch': 0.5555555555555556}
{'eval_loss': 0.4656805396080017, 'eval_spearman': 0.9183094760219042, 'eval_mae': 0.5367740988731384, 'eval_rmse': 0.6824079155921936, 'eval_runtime': 1.5244, 'eval_samples_per_second': 983.998, 'eval_steps_per_second': 15.744, 'epoch': 1.0}
{'loss': 0.3371, 'grad_norm': 5.505843639373779, 'learning_rate': 1.6049382716049385e-05, 'epoch': 1.1111111111111112}
{'loss': 0.2185, 'grad_norm': 10.383052825927734, 'learning_rate': 1.2962962962962964e-05, 'epoch': 1.6666666666666665}
{'eval_loss': 0.4677085876464844, 'eval_spearman': 0.9259714884819011, 'eval_mae': 0.5377089381217957, 'eval_rmse': 0.6838922500610352, 'eval_runtime': 1.524, 'eval_samples_per_second': 984.264, 'eval_steps_per_second': 15.748, 'epoch': 2.0}
{'loss': 0.1808, 'grad_norm': 3.789983034133911, 'learning_rate': 9.876543209876543e-06, 'epoch': 2.2222222222222223}
{'loss': 0.1301, 'grad_norm': 6.294739246368408, 'learning_rate': 6.790123456790124e-06, 'epoch': 2.7777777777777777}
{'eval_loss': 0.3681620955467224, 'eval_spearman': 0.926832373046208, 'eval_mae': 0.46515771746635437, 'eval_rmse': 0.6067636013031006, 'eval_runtime': 1.5148, 'eval_samples_per_second': 990.203, 'eval_steps_per_second': 15.843, 'epoch': 3.0}
{'loss': 0.0937, 'grad_norm': 4.935612678527832, 'learning_rate': 3.7037037037037037e-06, 'epoch': 3.3333333333333335}
{'loss': 0.0727, 'grad_norm': 4.791197776794434, 'learning_rate': 6.17283950617284e-07, 'epoch': 3.888888888888889}
{'eval_loss': 0.33288052678108215, 'eval_spearman': 0.9275928123619925, 'eval_mae': 0.4414530396461487, 'eval_rmse': 0.5769580006599426, 'eval_runtime': 1.549, 'eval_samples_per_second': 968.384, 'eval_steps_per_second': 15.494, 'epoch': 4.0}
{'train_runtime': 343.4143, 'train_samples_per_second': 66.963, 'train_steps_per_second': 4.193, 'train_loss': 0.45953169895542995, 'epoch': 4.0}
  Stage 1 (STS-B): dev Spearman = 0.9276
{'loss': 1.4952, 'grad_norm': 22.479246139526367, 'learning_rate': 4.9477221807318895e-06, 'epoch': 0.3508771929824561}
{'loss': 1.1037, 'grad_norm': 39.05589294433594, 'learning_rate': 4.5743091859596715e-06, 'epoch': 0.7017543859649122}
{'eval_loss': 0.9972909688949585, 'eval_spearman': 0.5961674532923014, 'eval_mae': 0.7786485552787781, 'eval_rmse': 0.9986445307731628, 'eval_runtime': 0.9664, 'eval_samples_per_second': 608.443, 'eval_steps_per_second': 10.348, 'epoch': 1.0}
{'loss': 0.8195, 'grad_norm': 14.598729133605957, 'learning_rate': 4.200896191187454e-06, 'epoch': 1.0526315789473684}
{'loss': 0.5663, 'grad_norm': 13.894265174865723, 'learning_rate': 3.827483196415236e-06, 'epoch': 1.4035087719298245}
{'loss': 0.556, 'grad_norm': 16.827478408813477, 'learning_rate': 3.4540702016430173e-06, 'epoch': 1.7543859649122808}
{'eval_loss': 0.9558018445968628, 'eval_spearman': 0.630817415057909, 'eval_mae': 0.7592988014221191, 'eval_rmse': 0.9776511788368225, 'eval_runtime': 0.9711, 'eval_samples_per_second': 605.52, 'eval_steps_per_second': 10.298, 'epoch': 2.0}
{'loss': 0.4836, 'grad_norm': 13.102275848388672, 'learning_rate': 3.0806572068707994e-06, 'epoch': 2.1052631578947367}
{'loss': 0.3718, 'grad_norm': 20.283748626708984, 'learning_rate': 2.7072442120985815e-06, 'epoch': 2.456140350877193}
{'loss': 0.3806, 'grad_norm': 19.06837272644043, 'learning_rate': 2.333831217326363e-06, 'epoch': 2.807017543859649}
{'eval_loss': 1.017531156539917, 'eval_spearman': 0.6424399268447278, 'eval_mae': 0.782096803188324, 'eval_rmse': 1.0087274312973022, 'eval_runtime': 0.9693, 'eval_samples_per_second': 606.638, 'eval_steps_per_second': 10.317, 'epoch': 3.0}
{'loss': 0.3113, 'grad_norm': 12.33879566192627, 'learning_rate': 1.960418222554145e-06, 'epoch': 3.1578947368421053}
{'loss': 0.2489, 'grad_norm': 16.991424560546875, 'learning_rate': 1.587005227781927e-06, 'epoch': 3.5087719298245617}
{'loss': 0.3043, 'grad_norm': 14.118278503417969, 'learning_rate': 1.213592233009709e-06, 'epoch': 3.8596491228070176}
{'eval_loss': 0.928851306438446, 'eval_spearman': 0.6484937377864648, 'eval_mae': 0.7497386932373047, 'eval_rmse': 0.9637693166732788, 'eval_runtime': 0.9687, 'eval_samples_per_second': 606.973, 'eval_steps_per_second': 10.323, 'epoch': 4.0}
{'loss': 0.2397, 'grad_norm': 12.330031394958496, 'learning_rate': 8.401792382374907e-07, 'epoch': 4.2105263157894735}
{'loss': 0.2129, 'grad_norm': 19.816913604736328, 'learning_rate': 4.667662434652726e-07, 'epoch': 4.56140350877193}
{'loss': 0.2222, 'grad_norm': 15.144268035888672, 'learning_rate': 9.335324869305452e-08, 'epoch': 4.912280701754386}
{'eval_loss': 0.9555407762527466, 'eval_spearman': 0.6535016807024829, 'eval_mae': 0.7595282196998596, 'eval_rmse': 0.9775177240371704, 'eval_runtime': 1.0069, 'eval_samples_per_second': 583.978, 'eval_steps_per_second': 9.932, 'epoch': 5.0}
{'train_runtime': 364.0136, 'train_samples_per_second': 31.318, 'train_steps_per_second': 3.915, 'train_loss': 0.5174726486206055, 'epoch': 5.0}
{'eval_loss': 1.0364583730697632, 'eval_spearman': 0.619981916986164, 'eval_mae': 0.7949003577232361, 'eval_rmse': 1.0180659294128418, 'eval_runtime': 1.5118, 'eval_samples_per_second': 615.148, 'eval_steps_per_second': 9.922, 'epoch': 5.0}
  → STS-B dev:    0.9276
  → Ambi dev:     0.6535 (best epoch 5)
  → Test ρ:       0.6200
  → Test acc-SD:  0.7613
  → Dev-test gap: 0.0335

============================================================
Seed 1337
============================================================

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at MoritzLaurer/deberta-v3-large-zeroshot-v2.0 and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([2]) in the checkpoint and torch.Size([1]) in the model instantiated
- classifier.weight: found shape torch.Size([2, 1024]) in the checkpoint and torch.Size([1, 1024]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'loss': 2.3583, 'grad_norm': 9.519967079162598, 'learning_rate': 1.9135802469135804e-05, 'epoch': 0.5555555555555556}
{'eval_loss': 0.3329595923423767, 'eval_spearman': 0.9220800086648019, 'eval_mae': 0.438912570476532, 'eval_rmse': 0.5770265460014343, 'eval_runtime': 1.5321, 'eval_samples_per_second': 979.042, 'eval_steps_per_second': 15.665, 'epoch': 1.0}
{'loss': 0.3579, 'grad_norm': 5.073480129241943, 'learning_rate': 1.6049382716049385e-05, 'epoch': 1.1111111111111112}
{'loss': 0.2428, 'grad_norm': 9.95948600769043, 'learning_rate': 1.2962962962962964e-05, 'epoch': 1.6666666666666665}
{'eval_loss': 0.3293745517730713, 'eval_spearman': 0.9269943068894387, 'eval_mae': 0.4390903413295746, 'eval_rmse': 0.5739116072654724, 'eval_runtime': 1.5232, 'eval_samples_per_second': 984.747, 'eval_steps_per_second': 15.756, 'epoch': 2.0}
{'loss': 0.1885, 'grad_norm': 4.572856426239014, 'learning_rate': 9.876543209876543e-06, 'epoch': 2.2222222222222223}
{'loss': 0.1397, 'grad_norm': 4.4056196212768555, 'learning_rate': 6.790123456790124e-06, 'epoch': 2.7777777777777777}
{'eval_loss': 0.3477056622505188, 'eval_spearman': 0.9272636287331507, 'eval_mae': 0.45466840267181396, 'eval_rmse': 0.5896657109260559, 'eval_runtime': 1.5209, 'eval_samples_per_second': 986.245, 'eval_steps_per_second': 15.78, 'epoch': 3.0}
{'loss': 0.0959, 'grad_norm': 3.9944050312042236, 'learning_rate': 3.7037037037037037e-06, 'epoch': 3.3333333333333335}
{'loss': 0.0802, 'grad_norm': 4.28859806060791, 'learning_rate': 6.17283950617284e-07, 'epoch': 3.888888888888889}
{'eval_loss': 0.33121564984321594, 'eval_spearman': 0.9270659914207784, 'eval_mae': 0.44056737422943115, 'eval_rmse': 0.5755133628845215, 'eval_runtime': 1.5829, 'eval_samples_per_second': 947.617, 'eval_steps_per_second': 15.162, 'epoch': 4.0}
{'train_runtime': 350.8068, 'train_samples_per_second': 65.552, 'train_steps_per_second': 4.105, 'train_loss': 0.48304560399717755, 'epoch': 4.0}
  Stage 1 (STS-B): dev Spearman = 0.9273
{'loss': 1.519, 'grad_norm': 30.44163703918457, 'learning_rate': 4.9477221807318895e-06, 'epoch': 0.3508771929824561}
{'loss': 1.0894, 'grad_norm': 53.425323486328125, 'learning_rate': 4.5743091859596715e-06, 'epoch': 0.7017543859649122}
{'eval_loss': 1.041091799736023, 'eval_spearman': 0.5870136184961768, 'eval_mae': 0.7949413657188416, 'eval_rmse': 1.020339012145996, 'eval_runtime': 0.9662, 'eval_samples_per_second': 608.586, 'eval_steps_per_second': 10.35, 'epoch': 1.0}
{'loss': 0.8184, 'grad_norm': 22.349315643310547, 'learning_rate': 4.200896191187454e-06, 'epoch': 1.0526315789473684}
{'loss': 0.5778, 'grad_norm': 23.667400360107422, 'learning_rate': 3.827483196415236e-06, 'epoch': 1.4035087719298245}
{'loss': 0.6187, 'grad_norm': 23.80632781982422, 'learning_rate': 3.4540702016430173e-06, 'epoch': 1.7543859649122808}
{'eval_loss': 1.2252271175384521, 'eval_spearman': 0.6244903583312781, 'eval_mae': 0.8658881187438965, 'eval_rmse': 1.1068998575210571, 'eval_runtime': 0.9775, 'eval_samples_per_second': 601.559, 'eval_steps_per_second': 10.231, 'epoch': 2.0}
{'loss': 0.5039, 'grad_norm': 19.359167098999023, 'learning_rate': 3.0806572068707994e-06, 'epoch': 2.1052631578947367}
{'loss': 0.3926, 'grad_norm': 20.913789749145508, 'learning_rate': 2.7072442120985815e-06, 'epoch': 2.456140350877193}
{'loss': 0.3797, 'grad_norm': 35.051361083984375, 'learning_rate': 2.333831217326363e-06, 'epoch': 2.807017543859649}
{'eval_loss': 1.0717720985412598, 'eval_spearman': 0.6462620980195052, 'eval_mae': 0.8029336929321289, 'eval_rmse': 1.035264253616333, 'eval_runtime': 0.9677, 'eval_samples_per_second': 607.614, 'eval_steps_per_second': 10.334, 'epoch': 3.0}
{'loss': 0.3286, 'grad_norm': 9.334348678588867, 'learning_rate': 1.960418222554145e-06, 'epoch': 3.1578947368421053}
{'loss': 0.29, 'grad_norm': 21.293352127075195, 'learning_rate': 1.587005227781927e-06, 'epoch': 3.5087719298245617}
{'loss': 0.3115, 'grad_norm': 28.59932518005371, 'learning_rate': 1.213592233009709e-06, 'epoch': 3.8596491228070176}
{'eval_loss': 1.0468899011611938, 'eval_spearman': 0.6459223085332142, 'eval_mae': 0.7926339507102966, 'eval_rmse': 1.0231764316558838, 'eval_runtime': 0.9699, 'eval_samples_per_second': 606.222, 'eval_steps_per_second': 10.31, 'epoch': 4.0}
{'loss': 0.2306, 'grad_norm': 16.740503311157227, 'learning_rate': 8.401792382374907e-07, 'epoch': 4.2105263157894735}
{'loss': 0.2228, 'grad_norm': 18.821319580078125, 'learning_rate': 4.667662434652726e-07, 'epoch': 4.56140350877193}
{'loss': 0.2075, 'grad_norm': 15.553242683410645, 'learning_rate': 9.335324869305452e-08, 'epoch': 4.912280701754386}
{'eval_loss': 1.062584638595581, 'eval_spearman': 0.6435502700750153, 'eval_mae': 0.8000398874282837, 'eval_rmse': 1.0308175086975098, 'eval_runtime': 1.0023, 'eval_samples_per_second': 586.64, 'eval_steps_per_second': 9.977, 'epoch': 5.0}
{'train_runtime': 690.8846, 'train_samples_per_second': 16.501, 'train_steps_per_second': 2.063, 'train_loss': 0.5296348163537812, 'epoch': 5.0}
{'eval_loss': 1.1039475202560425, 'eval_spearman': 0.609512380120176, 'eval_mae': 0.8152469992637634, 'eval_rmse': 1.0506891012191772, 'eval_runtime': 1.521, 'eval_samples_per_second': 611.44, 'eval_steps_per_second': 9.862, 'epoch': 5.0}
  → STS-B dev:    0.9273
  → Ambi dev:     0.6463 (best epoch 3)
  → Test ρ:       0.6095
  → Test acc-SD:  0.7559
  → Dev-test gap: 0.0367

============================================================
Seed 2024
============================================================

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at MoritzLaurer/deberta-v3-large-zeroshot-v2.0 and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([2]) in the checkpoint and torch.Size([1]) in the model instantiated
- classifier.weight: found shape torch.Size([2, 1024]) in the checkpoint and torch.Size([1, 1024]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'loss': 2.0304, 'grad_norm': 19.066776275634766, 'learning_rate': 1.9135802469135804e-05, 'epoch': 0.5555555555555556}
{'eval_loss': 0.37625667452812195, 'eval_spearman': 0.9218875696595947, 'eval_mae': 0.47293123602867126, 'eval_rmse': 0.6133976578712463, 'eval_runtime': 1.5459, 'eval_samples_per_second': 970.339, 'eval_steps_per_second': 15.525, 'epoch': 1.0}
{'loss': 0.3426, 'grad_norm': 9.62915325164795, 'learning_rate': 1.6049382716049385e-05, 'epoch': 1.1111111111111112}
{'loss': 0.2302, 'grad_norm': 5.918331146240234, 'learning_rate': 1.2962962962962964e-05, 'epoch': 1.6666666666666665}
{'eval_loss': 0.3276771605014801, 'eval_spearman': 0.9299140702797493, 'eval_mae': 0.4507625997066498, 'eval_rmse': 0.5724309086799622, 'eval_runtime': 1.5377, 'eval_samples_per_second': 975.49, 'eval_steps_per_second': 15.608, 'epoch': 2.0}
{'loss': 0.193, 'grad_norm': 5.235779285430908, 'learning_rate': 9.876543209876543e-06, 'epoch': 2.2222222222222223}
{'loss': 0.1274, 'grad_norm': 6.662353515625, 'learning_rate': 6.790123456790124e-06, 'epoch': 2.7777777777777777}
{'eval_loss': 0.3403134346008301, 'eval_spearman': 0.926360720186793, 'eval_mae': 0.45125359296798706, 'eval_rmse': 0.5833638906478882, 'eval_runtime': 1.5466, 'eval_samples_per_second': 969.873, 'eval_steps_per_second': 15.518, 'epoch': 3.0}
{'loss': 0.0955, 'grad_norm': 4.298173427581787, 'learning_rate': 3.7037037037037037e-06, 'epoch': 3.3333333333333335}
{'loss': 0.079, 'grad_norm': 2.8503592014312744, 'learning_rate': 6.17283950617284e-07, 'epoch': 3.888888888888889}
{'eval_loss': 0.32272741198539734, 'eval_spearman': 0.9288348655852748, 'eval_mae': 0.4391463100910187, 'eval_rmse': 0.5680909752845764, 'eval_runtime': 1.5998, 'eval_samples_per_second': 937.63, 'eval_steps_per_second': 15.002, 'epoch': 4.0}
{'train_runtime': 344.0674, 'train_samples_per_second': 66.836, 'train_steps_per_second': 4.185, 'train_loss': 0.43243533985482324, 'epoch': 4.0}
  Stage 1 (STS-B): dev Spearman = 0.9299
{'loss': 1.5268, 'grad_norm': 19.83812141418457, 'learning_rate': 4.9477221807318895e-06, 'epoch': 0.3508771929824561}
{'loss': 1.0275, 'grad_norm': 37.69435501098633, 'learning_rate': 4.5743091859596715e-06, 'epoch': 0.7017543859649122}
{'eval_loss': 1.0386711359024048, 'eval_spearman': 0.6086641394719444, 'eval_mae': 0.8067203164100647, 'eval_rmse': 1.0191521644592285, 'eval_runtime': 0.9652, 'eval_samples_per_second': 609.216, 'eval_steps_per_second': 10.361, 'epoch': 1.0}
{'loss': 0.8099, 'grad_norm': 39.021114349365234, 'learning_rate': 4.200896191187454e-06, 'epoch': 1.0526315789473684}
{'loss': 0.5822, 'grad_norm': 32.6979866027832, 'learning_rate': 3.827483196415236e-06, 'epoch': 1.4035087719298245}
{'loss': 0.5861, 'grad_norm': 18.268962860107422, 'learning_rate': 3.4540702016430173e-06, 'epoch': 1.7543859649122808}
{'eval_loss': 1.0126017332077026, 'eval_spearman': 0.6282147457422591, 'eval_mae': 0.7867338061332703, 'eval_rmse': 1.0062811374664307, 'eval_runtime': 0.9715, 'eval_samples_per_second': 605.24, 'eval_steps_per_second': 10.293, 'epoch': 2.0}
{'loss': 0.5158, 'grad_norm': 8.87297534942627, 'learning_rate': 3.0806572068707994e-06, 'epoch': 2.1052631578947367}
{'loss': 0.3892, 'grad_norm': 20.93453025817871, 'learning_rate': 2.7072442120985815e-06, 'epoch': 2.456140350877193}
{'loss': 0.377, 'grad_norm': 10.293861389160156, 'learning_rate': 2.333831217326363e-06, 'epoch': 2.807017543859649}
{'eval_loss': 1.1386791467666626, 'eval_spearman': 0.6390172545602677, 'eval_mae': 0.8355787396430969, 'eval_rmse': 1.0670890808105469, 'eval_runtime': 0.9709, 'eval_samples_per_second': 605.637, 'eval_steps_per_second': 10.3, 'epoch': 3.0}
{'loss': 0.3242, 'grad_norm': 19.620038986206055, 'learning_rate': 1.960418222554145e-06, 'epoch': 3.1578947368421053}
{'loss': 0.2754, 'grad_norm': 19.932567596435547, 'learning_rate': 1.587005227781927e-06, 'epoch': 3.5087719298245617}
{'loss': 0.2684, 'grad_norm': 32.563106536865234, 'learning_rate': 1.213592233009709e-06, 'epoch': 3.8596491228070176}
{'eval_loss': 1.1806702613830566, 'eval_spearman': 0.6335330471981122, 'eval_mae': 0.8528460264205933, 'eval_rmse': 1.0865864753723145, 'eval_runtime': 0.9699, 'eval_samples_per_second': 606.24, 'eval_steps_per_second': 10.31, 'epoch': 4.0}
{'loss': 0.2423, 'grad_norm': 9.231135368347168, 'learning_rate': 8.401792382374907e-07, 'epoch': 4.2105263157894735}
{'loss': 0.2344, 'grad_norm': 23.561885833740234, 'learning_rate': 4.667662434652726e-07, 'epoch': 4.56140350877193}
{'loss': 0.2261, 'grad_norm': 10.9501314163208, 'learning_rate': 9.335324869305452e-08, 'epoch': 4.912280701754386}
{'eval_loss': 1.070273756980896, 'eval_spearman': 0.6344814354539102, 'eval_mae': 0.8038797378540039, 'eval_rmse': 1.0345402956008911, 'eval_runtime': 0.992, 'eval_samples_per_second': 592.746, 'eval_steps_per_second': 10.081, 'epoch': 5.0}
{'train_runtime': 345.0799, 'train_samples_per_second': 33.036, 'train_steps_per_second': 4.129, 'train_loss': 0.5225596491495769, 'epoch': 5.0}
{'eval_loss': 1.1423680782318115, 'eval_spearman': 0.6222625638229418, 'eval_mae': 0.8418380618095398, 'eval_rmse': 1.0688161849975586, 'eval_runtime': 1.5151, 'eval_samples_per_second': 613.811, 'eval_steps_per_second': 9.9, 'epoch': 5.0}
  → STS-B dev:    0.9299
  → Ambi dev:     0.6390 (best epoch 3)
  → Test ρ:       0.6223
  → Test acc-SD:  0.7226
  → Dev-test gap: 0.0168


============================================================
MULTI-SEED CURRICULUM RESULTS (STS-B -> AmbiStory)
============================================================

Test Spearman:        0.6173 ± 0.0056
Test Acc-within-SD:   0.7466 ± 0.0171
AmbiStory dev ρ:      0.6463 ± 0.0059
Dev -> test gap:       0.0290 ± 0.0088
Best epoch (Stage 2): 3.7 (range: 3–5)

Per seed:
  seed=42: test ρ=0.6200, gap=0.0335, best_epoch=5
  seed=1337: test ρ=0.6095, gap=0.0367, best_epoch=3
  seed=2024: test ρ=0.6223, gap=0.0168, best_epoch=3

Vs baseline (single seed):
  Δ Test Spearman:    -0.0163
  Δ Test Acc-SD:      -0.0276
  Δ Dev-test gap:     -0.0184

In [14]:
# === V2 ABLATION: shorter STS-B ===

STSB_CONFIG_V2 = {
    "lr": 2e-5,
    "bs": 16,
    "epochs": 2,
    "warmup": 0.1,
}

model = AutoModelForSequenceClassification.from_pretrained(
    model_id,
    num_labels=1,
    problem_type="regression",
    ignore_mismatched_sizes=True,
)

stsb_args_v2 = TrainingArguments(
    output_dir="./curriculum_v2/stsb_seed42",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=STSB_CONFIG_V2["lr"],
    per_device_train_batch_size=STSB_CONFIG_V2["bs"],
    per_device_eval_batch_size=64,
    num_train_epochs=STSB_CONFIG_V2["epochs"],
    weight_decay=0.01,
    warmup_ratio=STSB_CONFIG_V2["warmup"],
    bf16=True,
    load_best_model_at_end=True,
    metric_for_best_model="spearman",
    greater_is_better=True,
    save_total_limit=1,
    logging_steps=200,
    report_to="none",
    seed=42,
    disable_tqdm=True,
)

stsb_trainer_v2 = Trainer(
    model=model,
    args=stsb_args_v2,
    data_collator=data_collator,
    train_dataset=stsb_tokenized["train"],
    eval_dataset=stsb_tokenized["validation"],
    tokenizer=tokenizer,
    compute_metrics=metric_computation,
)

stsb_trainer_v2.train()
print(f"Stage 1 (2 epochs) STS-B dev: {stsb_trainer_v2.state.best_metric:.4f}")
stsb_trainer_v2.save_model("./curriculum_v2/stsb_seed42/final")

del model, stsb_trainer_v2
gc.collect()
torch.cuda.empty_cache()

model = AutoModelForSequenceClassification.from_pretrained("./curriculum_v2/stsb_seed42/final")

ambi_args_v2 = TrainingArguments(
    output_dir="./curriculum_v2/ambistory_seed42",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-6,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=64,
    num_train_epochs=5,
    weight_decay=0.01,
    warmup_ratio=0.06,
    bf16=True,
    load_best_model_at_end=True,
    metric_for_best_model="spearman",
    greater_is_better=True,
    save_total_limit=1,
    logging_steps=100,
    report_to="none",
    seed=42,
    disable_tqdm=True,
)

ambi_trainer_v2 = Trainer(
    model=model,
    args=ambi_args_v2,
    data_collator=data_collator,
    train_dataset=tokenized_datasets["ambistory_train_set"],
    eval_dataset=tokenized_datasets["ambistory_validation_set"],
    tokenizer=tokenizer,
    compute_metrics=metric_computation,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)],
)

ambi_trainer_v2.train()

test_metrics = ambi_trainer_v2.evaluate(tokenized_datasets["ambistory_test_set"])
test_preds = ambi_trainer_v2.predict(tokenized_datasets["ambistory_test_set"]).predictions.squeeze()
test_labels = ambistory_test_df["average"].to_numpy()
test_stdev = ambistory_test_df["stdev"].to_numpy()
threshold = np.maximum(test_stdev, 1.0)
acc_within_sd = float(np.mean(np.abs(test_preds - test_labels) <= threshold))

print(f"\n=== V2 Ablation (STS-B 2 epochs, seed=42) ===")
print(f"  Test ρ:       {test_metrics['eval_spearman']:.4f}")
print(f"  Test acc-SD:  {acc_within_sd:.4f}")
print(f"  Dev-test gap: {ambi_trainer_v2.state.best_metric - test_metrics['eval_spearman']:.4f}")
print(f"\nReference numbers:")
print(f"  Baseline (single seed): test ρ=0.6336")
print(f"  STS-B v1 mean (3 seeds): test ρ=0.617 ± 0.006")
print(f"  STS-B v2 seed=42:       test ρ={test_metrics['eval_spearman']:.4f}")

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at MoritzLaurer/deberta-v3-large-zeroshot-v2.0 and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([2]) in the checkpoint and torch.Size([1]) in the model instantiated
- classifier.weight: found shape torch.Size([2, 1024]) in the checkpoint and torch.Size([1, 1024]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

{'loss': 1.8236, 'grad_norm': 10.964653015136719, 'learning_rate': 1.6049382716049385e-05, 'epoch': 0.5555555555555556}
{'eval_loss': 0.42056527733802795, 'eval_spearman': 0.9086176837969095, 'eval_mae': 0.4921852946281433, 'eval_rmse': 0.6485099792480469, 'eval_runtime': 1.5309, 'eval_samples_per_second': 979.811, 'eval_steps_per_second': 15.677, 'epoch': 1.0}
{'loss': 0.3513, 'grad_norm': 7.462048053741455, 'learning_rate': 9.876543209876543e-06, 'epoch': 1.1111111111111112}
{'loss': 0.217, 'grad_norm': 6.169938087463379, 'learning_rate': 3.7037037037037037e-06, 'epoch': 1.6666666666666665}
{'eval_loss': 0.34636059403419495, 'eval_spearman': 0.9233200343963102, 'eval_mae': 0.44844916462898254, 'eval_rmse': 0.5885241031646729, 'eval_runtime': 1.5623, 'eval_samples_per_second': 960.139, 'eval_steps_per_second': 15.362, 'epoch': 2.0}
{'train_runtime': 193.0644, 'train_samples_per_second': 59.555, 'train_steps_per_second': 3.729, 'train_loss': 0.6972854746712579, 'epoch': 2.0}
Stage 1 (2 epochs) STS-B dev: 0.9233
{'loss': 1.5144, 'grad_norm': 20.59906005859375, 'learning_rate': 4.9477221807318895e-06, 'epoch': 0.3508771929824561}
{'loss': 1.0566, 'grad_norm': 32.241512298583984, 'learning_rate': 4.5743091859596715e-06, 'epoch': 0.7017543859649122}
{'eval_loss': 1.0391994714736938, 'eval_spearman': 0.5814627926780119, 'eval_mae': 0.7998689413070679, 'eval_rmse': 1.019411325454712, 'eval_runtime': 0.9701, 'eval_samples_per_second': 606.1, 'eval_steps_per_second': 10.308, 'epoch': 1.0}
{'loss': 0.8232, 'grad_norm': 16.572635650634766, 'learning_rate': 4.200896191187454e-06, 'epoch': 1.0526315789473684}
{'loss': 0.6028, 'grad_norm': 12.817338943481445, 'learning_rate': 3.827483196415236e-06, 'epoch': 1.4035087719298245}
{'loss': 0.5828, 'grad_norm': 57.232391357421875, 'learning_rate': 3.4540702016430173e-06, 'epoch': 1.7543859649122808}
{'eval_loss': 1.0665922164916992, 'eval_spearman': 0.6171392788736944, 'eval_mae': 0.7953833341598511, 'eval_rmse': 1.0327595472335815, 'eval_runtime': 0.9703, 'eval_samples_per_second': 605.988, 'eval_steps_per_second': 10.306, 'epoch': 2.0}
{'loss': 0.4905, 'grad_norm': 18.899883270263672, 'learning_rate': 3.0806572068707994e-06, 'epoch': 2.1052631578947367}
{'loss': 0.3999, 'grad_norm': 19.457778930664062, 'learning_rate': 2.7072442120985815e-06, 'epoch': 2.456140350877193}
{'loss': 0.397, 'grad_norm': 17.784353256225586, 'learning_rate': 2.333831217326363e-06, 'epoch': 2.807017543859649}
{'eval_loss': 1.0314929485321045, 'eval_spearman': 0.641485964799249, 'eval_mae': 0.7802154421806335, 'eval_rmse': 1.0156244039535522, 'eval_runtime': 0.9625, 'eval_samples_per_second': 610.933, 'eval_steps_per_second': 10.39, 'epoch': 3.0}
{'loss': 0.3219, 'grad_norm': 14.744874954223633, 'learning_rate': 1.960418222554145e-06, 'epoch': 3.1578947368421053}
{'loss': 0.2648, 'grad_norm': 8.976621627807617, 'learning_rate': 1.587005227781927e-06, 'epoch': 3.5087719298245617}
{'loss': 0.3194, 'grad_norm': 12.851616859436035, 'learning_rate': 1.213592233009709e-06, 'epoch': 3.8596491228070176}
{'eval_loss': 0.9676070213317871, 'eval_spearman': 0.6448944842609389, 'eval_mae': 0.7585264444351196, 'eval_rmse': 0.983670175075531, 'eval_runtime': 0.9639, 'eval_samples_per_second': 610.015, 'eval_steps_per_second': 10.374, 'epoch': 4.0}
{'loss': 0.2737, 'grad_norm': 11.936142921447754, 'learning_rate': 8.401792382374907e-07, 'epoch': 4.2105263157894735}
{'loss': 0.2271, 'grad_norm': 25.54159164428711, 'learning_rate': 4.667662434652726e-07, 'epoch': 4.56140350877193}
{'loss': 0.2507, 'grad_norm': 9.34929370880127, 'learning_rate': 9.335324869305452e-08, 'epoch': 4.912280701754386}
{'eval_loss': 1.0319589376449585, 'eval_spearman': 0.6479469774537565, 'eval_mae': 0.7817593812942505, 'eval_rmse': 1.0158536434173584, 'eval_runtime': 0.9917, 'eval_samples_per_second': 592.933, 'eval_steps_per_second': 10.084, 'epoch': 5.0}
{'train_runtime': 748.0257, 'train_samples_per_second': 15.24, 'train_steps_per_second': 1.905, 'train_loss': 0.5326403340122156, 'epoch': 5.0}
{'eval_loss': 1.038823127746582, 'eval_spearman': 0.6264315742170684, 'eval_mae': 0.7982202172279358, 'eval_rmse': 1.0192267894744873, 'eval_runtime': 1.5275, 'eval_samples_per_second': 608.846, 'eval_steps_per_second': 9.82, 'epoch': 5.0}

=== V2 Ablation (STS-B 2 epochs, seed=42) ===
  Test ρ:       0.6264
  Test acc-SD:  0.7688
  Dev-test gap: 0.0215

Reference numbers:
  Baseline (single seed): test ρ=0.6336
  STS-B v1 mean (3 seeds): test ρ=0.617 ± 0.006
  STS-B v2 seed=42:       test ρ=0.6264